services:
  websocket:
    build:
      context: ./server
    environment:
      - PORT=3000
      - MINIO_ENDPOINT=minio
      - FORCE_HTTPS=true
    restart: always

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  web:
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - websocket
      - minio

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "web:80"
    ports:
      - "4040:4040"
    depends_on:
      - web
    restart: always

volumes:
  minio_data:
