version: '3.8'

services:
  hub:
    build:
      context: ./hub
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: always

  websocket:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HUB_URL=ws://hub:3001
      - REGION=${REGION:-default}
      - PUBLIC_WS_URL=${PUBLIC_WS_URL:-ws://localhost:3000}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:9000}
      - FORCE_HTTPS=true
    depends_on:
      - hub
      - minio
    restart: always

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  web:
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - websocket
      - minio

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "web:80"
    ports:
      - "4040:4040"
    depends_on:
      - web
    restart: always

volumes:
  minio_data:
